# Enviroment config
env: staging

# DataSource config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ${REDDINGTON_DATABASE_PASSWORD}
    url: ${REDDINGTON_DATABASE_URL}
    username: ${REDDINGTON_DATABASE_USERNAME}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

# Sentry config
sentry:
  dsn: ${REDDINGTON_SENTRY_DSN}
